# Render deployment configuration
services:
  - type: web
    name: hackrx-document-intelligence
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python start.py"
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 10000
