# Render deployment configuration
services:
  - type: web
    name: hackrx-document-intelligence
    env: python
    buildCommand: "echo 'No dependencies'"
    startCommand: "python hackrx_minimal.py"
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 10000
